// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghomfxzntlqvpgnuxubk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdob21meHpudGxxdnBnbnV4dWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwOTYwMzcsImV4cCI6MjA4MTY3MjAzN30.zBMYTWU2PJfIwwnclpgeid6668GsadAGTMtpxmV25iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});